name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install ALL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          unzip openjdk-17-jdk git autoconf libtool pkg-config \
          zlib1g-dev libncurses6-dev libncursesw6-dev libtinfo6 \
          cmake libffi-dev libssl-dev python3-dev
        
        pip install --upgrade pip
        pip install wheel setuptools cython buildozer plyer kivy
        pip install "setuptools<67.0"
    
    - name: Configure Buildozer
      run: |
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
        # Автоматически обновляем spec файл
        sed -i 's/^requirements = .*/requirements = python3,kivy==2.1.0,plyer,setuptools,cython/' buildozer.spec
        sed -i 's/^android.ndk = .*/android.ndk = 23b/' buildozer.spec
        sed -i 's/^android.arch = .*/android.arch = armeabi-v7a/' buildozer.spec
        sed -i 's/^android.api = .*/android.api = 34/' buildozer.spec
        sed -i 's/^android.minapi = .*/android.minapi = 21/' buildozer.spec
        
        # Добавляем новые настройки для совместимости
        echo "android.allow_backup = False" >> buildozer.spec
        echo "p4a.branch = master" >> buildozer.spec
    
    - name: Build APK
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        buildozer android clean
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: victory-app
        path: bin/*.apk
        retention-days: 1
        name: victory-app
        path: bin/*.apk
        retention-days: 1
