name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo docker --version
        
    - name: Build APK with Docker
      run: |
        # Создаем Dockerfile
        cat > Dockerfile <<EOF
        FROM thomasschmied/buildozer:latest
        WORKDIR /app
        COPY . .
        RUN buildozer android clean
        CMD ["buildozer", "-v", "android", "debug"]
        EOF
        
        # Собираем образ
        sudo docker build -t victory-app-builder .
        
        # Запускаем сборку
        sudo docker run --rm -v $(pwd)/bin:/app/bin victory-app-builder
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: victory-app
        path: bin/*.apk
        retention-days: 1
