name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libreadline-dev \
            libffi-dev \
            libsqlite3-dev \
            wget \
            unzip

      - name: Install Buildozer
        run: |
          pip install --user --upgrade pip
          pip install --user buildozer cython==0.29.33

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O ~/cmdline-tools.zip
          unzip -q ~/cmdline-tools.zip -d ~/.buildozer/android/platform/
          mv ~/.buildozer/android/platform/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

      - name: Initialize Buildozer
        run: |
          buildozer init
          buildozer android update

      - name: Build APK
        run: |
          buildozer -v android debug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: victory-app
          path: bin/*.apk
          retention-days: 3
