name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60  # Увеличено время выполнения
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          unzip openjdk-17-jdk git autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev python3-dev python3-venv \
          ffmpeg wget
        
        # Создаем структуру Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p android-sdk
        unzip -q cmdline-tools.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        rm cmdline-tools.zip
        
        # Настраиваем переменные окружения
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
    
    - name: Set up Android SDK
      run: |
        # Принимаем лицензии
        yes | sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT
        
        # Устанавливаем необходимые компоненты
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" --sdk_root=$ANDROID_SDK_ROOT
        
        # Скачиваем и устанавливаем NDK 25b
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d $ANDROID_SDK_ROOT
        mv $ANDROID_SDK_ROOT/android-ndk-r25b $ANDROID_SDK_ROOT/ndk/25b
        rm android-ndk-r25b-linux.zip
        
        # Устанавливаем переменные окружения для NDK
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25b" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25b" >> $GITHUB_ENV
        echo "export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25b" >> $BASH_ENV
        
        # Создаем символическую ссылку для совместимости
        mkdir -p $ANDROID_SDK_ROOT/tools/bin
        ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager $ANDROID_SDK_ROOT/tools/bin/sdkmanager
    
    - name: Set up Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
        echo "PATH=$PWD/venv/bin:$PATH" >> $GITHUB_ENV
        pip install --upgrade pip wheel setuptools
    
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install cython==0.29.36 buildozer==1.5.0 plyer==2.1.0 kivy==2.3.0
        pip install git+https://github.com/kivy/python-for-android.git@master
    
    - name: Configure Buildozer
      run: |
        # Создаем buildozer.spec
        cat <<EOF > buildozer.spec
        [app]
        title = VictoryApp
        package.name = victoryapp
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas,wav
        version = 1.0
        requirements = python3,kivy==2.3.0,plyer,setuptools,cython
        orientation = portrait
        fullscreen = 0
        android.permissions = INTERNET
        android.api = 34
        android.minapi = 21
        android.ndk = 25b
        android.ndk_path = $GITHUB_WORKSPACE/android-sdk/ndk/25b
        android.sdk_path = $GITHUB_WORKSPACE/android-sdk
        android.build_tools_version = 34.0.0
        android.archs = armeabi-v7a
        android.allow_backup = False
        p4a.branch = master
        android.sdkmanager = $GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin/sdkmanager
        EOF
        
        # Конвертируем звук если нужно
        if [ -f victory.wav ]; then
          ffmpeg -y -i victory.wav -acodec pcm_s16le -ar 44100 -ac 1 victory_fixed.wav
          mv victory_fixed.wav victory.wav
        fi
    
    - name: Patch python-for-android
      run: |
        # Отключаем автоматическую загрузку NDK в python-for-android
        if [ -d ".buildozer/android/platform/python-for-android" ]; then
          find .buildozer/android/platform/python-for-android -name '__init__.py' -exec \
            sed -i '/self\._install_android_ndk()/d' {} \;
        fi
    
    - name: Build APK
      run: |
        source venv/bin/activate
        
        # Устанавливаем критические переменные
        export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk
        export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25b
        export NDK_HOME=$ANDROID_SDK_ROOT/ndk/25b
        
        # Очистка предыдущих сборок
        buildozer android clean
        rm -rf .buildozer/android/platform/build-* .buildozer/android/platform/dists
        
        # Создаем необходимые директории
        mkdir -p .buildozer/android/platform/python-for-android
        mkdir -p bin
        
        # Исправляем путь к sdkmanager
        sed -i "s|android.sdkmanager = .*|android.sdkmanager = $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager|" buildozer.spec
        
        # Собираем APK
        buildozer -v android debug
        
        # Проверяем наличие APK
        if [ ! -f bin/*.apk ]; then
          echo "::error::APK file not found!"
          exit 1
        fi
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: victory-app
        path: bin/*.apk
        retention-days: 1
